### ISSUE TITLE
Django 2 support

### ISSUE THREAD

**Issue by eiva** [peterdemin/django-pyodbc-lb#1]
Could you please add support of Django 2+  including installation of more recent django-pyodbc-azure?

**Comment by peterdemin** [comment]
Thanks for asking! The free community edition of Django-pyodbc-lb does not include this feature.
If your organization can benefit from Django 2.0 support, you're welcome to sponsor its development.
The price is $100.00, and I will implement the feature ASAP after payment.

**Comment by Jskarie** [comment]
Is this offer still open.  I sponsor it's development and you will add Django 2.2 support?

**Comment by peterdemin** [comment]
Nah, I'm done with SQL Server and Python
